### ISSUE TITLE
使用方法能否一次全部引入

### ISSUE THREAD

**Issue by jgsrty** [hamger/hg-vcomponents#1]
就像市面上流行的UI库一样 直接在main.js中 Vue.use(组件) 这种方式引入呢

**Comment by hamger** [comment]
Vue.use 的形式我之前考虑过，适合与具有统一风格的一整套UI库，由于 hg-vcomponents 只提供一些零散的小组件，一般只有单个引入的情况，所以暂时不支持  Vue.use 的引入方式，后续会考虑做支持。

**Comment by jgsrty** [comment]
:100:
